/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN PC
 */
import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
public class Honor extends javax.swing.JDialog {
String url="jdbc:mysql://localhost:3306/mydb";
                                String user="root";
                                String pass="";
    /**
     * Creates new form Honor
     */
    public Honor() {

        initComponents();
    
         //System.out.print("entered");
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 27, 33));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("H:\\mobilesa\\honor.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel1.setBackground(new java.awt.Color(244, 169, 80));
        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 169, 80));
        jLabel1.setText("HONOR 6S");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, 50));

        jTextPane1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jTextPane1.setText("FEATURES:        \n        1) 13MP+2MP dual rare primary camera and 8MP front facing camera \n\n        2) 15.90 centimeters (6.26-inch) with 1520 x 720 pixels resolution | 269 ppi pixel density \n        \n        3) Memory, Storage and SIM: 4GB RAM 32GB internal memory expandable up to 256GB | Dual SIM (nano+nano) dual-standby (4G+4G) \n\n        4) Android +EMUI8.2 Lite v8.1 operating system with 1.8GHz Snapdragon 632 octa core processor \n\n        5) 4000mAH lithium-polymer battery \n\n        6) 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries and 3 months for Data/USB cable from the date of purchase");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 210, 240));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jButton1.setText("Buy");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 90, 40));

        jButton2.setText("<--Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 490));

        pack();
    }// </editor-fold>

   private void ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
          String s=evt.getActionCommand();
        
  
      

             if(s.equals("Buy"))
                     {
                        
                //        String sql="INSERT INTO APP.BUYMENU(NAME,CAMERA, BATTERY) VALUES ('Samsung Galaxy s6','16MP|5MP', '4000')";
                                
                                Connection con=null;
                                ResultSet res=null;
                                String query="insert into  tab(mob,val,det) values(?,?,?)";
                                try{
                                    
             
                                    con=DriverManager.getConnection(url,user,pass);
                                    PreparedStatement  stmt= con.prepareStatement(query);
                                    stmt.setString(1,"HONOR6S ");
                                   // System.out.print("entered");
                                    stmt.setInt(2,10000);
                                    stmt.setString(3,"*13+2MP *4GB RAM *32GB MEMORY *4000MAH");
                                    int i=stmt.executeUpdate();
           
                                    con.close();
                                    }
                                catch(Exception e)
                                    {

                                    }
                                this.setVisible(false);


                        mini z=new mini();
                       
                        

                      

     }
             else
             {
                 Mainpage ob1=new Mainpage();
        ob1.setVisible(true);
        this.setVisible(false);
             }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Honor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Honor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Honor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Honor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Honor dialog = new Honor();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration
}

