
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN PC
 */
public class nokia extends javax.swing.JDialog {
    String url="jdbc:mysql://localhost:3306/mydb";
                                String user="root";
                                String pass="";

    /**
     * Creates new form nokia
     */
    public nokia() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 230, 124));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 95, 45));
        jLabel1.setText("NOKIA 6.1 plus");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("H:\\mobilesa\\nokia.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 180));

        jTextPane1.setText("FEATURES:\n        1) 16MP+5MP rear camera | 16MP front facing camera \n\n        2) 14.732 centimeters (5.8-inch) with 1080 x 2280 pixels resolution \n\n        3) Memory, Storage and SIM: 6GB RAM | 64GB internal memory | Expandable to 400 GB |Dual SIM dual-standby (4G+4G) \n\n        4) Android v8 Oreo operating system with Qualcomm Snapdragon SD 636 quad core processor \n\n        5)3060mAH lithium-ion battery \n\n        6) 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase \n\n        7) Box includes: Charger and Data cable");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 210, 240));

        jButton1.setBackground(new java.awt.Color(204, 102, 0));
        jButton1.setText("Buy");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 80, 30));

        jButton2.setText("<--Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 480));

        pack();
    }// </editor-fold>

    private void ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
          String s=evt.getActionCommand();
        
    //}
     //private void ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        
      

             if(s.equals("Buy"))
                     {
                         Connection con=null;
                                ResultSet res=null;
                                String query="insert into  tab(mob,val,det) values(?,?,?)";
                                try{
                                    //Class.forName("com.mysql.jdbc.Driver");
                               
            
                                //System.out.print("entered");
             
                                    con=DriverManager.getConnection(url,user,pass);
                                    PreparedStatement  stmt= con.prepareStatement(query);
                                    stmt.setString(1,"NOKIA 6.1PLUS ");
                                   // System.out.print("entered");
                                    stmt.setInt(2,19000);
                                    stmt.setString(3,"*15+5MP *4GB RAM *32GB MEMORY *3010MAH");
                                    int i=stmt.executeUpdate();
            /*while(res.next())
            {
                String ITEM=res.getString("ITEM");
                int values=res.getInt("values");
                System.out.println(ITEM);
                
            }*/
             //System.out.print("entered");
                                    con.close();
                                    }
                                catch(Exception e)
                                    {

                                    }
                        this.setVisible(false);
                        String sql="INSERT INTO APP.BUYMENU(NAME,CAMERA, BATTERY) VALUES ('Samsung Galaxy s6','16MP|5MP', '4000')";

                        mini z=new mini();

                      //  sappai k=new sappai();

     }
             else
             {
                 Mainpage ob1=new Mainpage();
        ob1.setVisible(true);
        this.setVisible(false);
             }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nokia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nokia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nokia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nokia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                nokia dialog = new nokia();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration
}

