
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN PC
 */
public class vivo extends javax.swing.JDialog {

    String url="jdbc:mysql://localhost:3306/mydb";
                                String user="root";
                                String pass="";
    /**
     * Creates new form vivo
     */
    public vivo() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(41, 27, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("H:\\mobilesa\\vivo.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, -1));

        jTextPane1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jTextPane1.setText("FEATURES:\n        1) 6 GB RAM | 128 GB ROM | Expandable Upto 256 GB \n\n        2) 16.59 cm (6.53 inch) FHD+ Display \n\n        3) 16MP + 8MP + 2MP | 32MP Front Camera \n\n        4) 5000 mAh Battery \n\n        5) Qualcomm Snapdragon 712 AIE Octa Core 2.3GHz Processor \n\n        6) Triple Card Slot \n\n        7) Fast Charging");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 240, 230));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        jButton1.setText("Buy");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 80, 40));

        jButton2.setText("<--Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setBackground(new java.awt.Color(204, 169, 105));
        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 169, 105));
        jLabel1.setText("VIVO Z1 PRO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 250, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        pack();
    }// </editor-fold>

    private void ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
          String s=evt.getActionCommand();
        
    //}
     //private void ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        
      

             if(s.equals("Buy"))
                     {
                         Connection con=null;
                                ResultSet res=null;
                                String query="insert into  tab(mob,val,det) values(?,?,?)";
                                try{
                                    //Class.forName("com.mysql.jdbc.Driver");
                               
            
                                //System.out.print("entered");
             
                                    con=DriverManager.getConnection(url,user,pass);
                                    PreparedStatement  stmt= con.prepareStatement(query);
                                    stmt.setString(1,"VIVOZ1PRO ");
                                   // System.out.print("entered");
                                    stmt.setInt(2,25000);
                                    stmt.setString(3,"*16+8MP *4GB RAM *64GB MEMORY *5000MAH");
                                    int i=stmt.executeUpdate();
            /*while(res.next())
            {
                String ITEM=res.getString("ITEM");
                int values=res.getInt("values");
                System.out.println(ITEM);
                
            }*/
             //System.out.print("entered");
                                    con.close();
                                    }
                                catch(Exception e)
                                    {

                                    }
                        this.setVisible(false);
//                        String sql="INSERT INTO APP.BUYMENU(NAME,CAMERA, BATTERY) VALUES ('Samsung Galaxy s6','16MP|5MP', '4000')";

                       mini z=new mini();
                      //  sappai k=new sappai();

     }
             else
             {
                 Mainpage ob1=new Mainpage();
        ob1.setVisible(true);
        this.setVisible(false);
             }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vivo dialog = new vivo();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration
}


